[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://deep-research-nu-swart.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
