[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://deepresearch-2fou.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
